#  docker run -d --name test_db_2 -p 5432:5432 -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=test_db postgres:14.0-alpine
version: '3.1'
services:
  db:
    container_name: storage
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"